{
 "title": "Details",
 "time": { "from": "2022-11-12T12:30:00.000Z", "to": "2023-05-24T06:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "DeviceList",
    "label": "Device",
    "query": "select distinct device_identifier from kpi_1d;"
   },
   {
    "name": "OrganizationList",
    "label": "Organization",
    "query": "select distinct org_identifier  from kpi_1d;"
   },
   {
    "name": "AlertList",
    "label": "Alert",
    "query": "SELECT DISTINCT name FROM kpi_type;"
   },
   {
    "name": "YearMonth",
    "label": "Period",
    "query": "SELECT distinct TO_CHAR (time, 'YYYY-MM') FROM kpi_1d;"
   },
   { "name": "Warning", "label": "Select only one Month!" }
  ]
 },
 "panels": [
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT device_identifier)\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nWHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) "
    }
   ]
  },
  {
   "title": "Total Organizations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT org_identifier)\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nWHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) "
    }
   ]
  },
  {
   "title": "Monthly Inactive Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n\tcount(perfectMonth) from (\r\nselect  (avg(kpi_alert_count)) as perfectMonth, TO_CHAR(time, 'YYYY-MM') as ym\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) \r\nAND name IN ($AlertList)\r\ngroup by TO_CHAR(time, 'YYYY-MM'), device_identifier,org_identifier, kpi_type_code) sub\r\nwhere perfectMonth = 0"
    }
   ]
  },
  {
   "title": "Monthly Active Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n\tcount(perfectMonth) from (\r\nselect  (avg(kpi_alert_count)) as perfectMonth, TO_CHAR(time, 'YYYY-MM') as ym\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) \r\nAND name IN ($AlertList)\r\ngroup by TO_CHAR(time, 'YYYY-MM'), device_identifier,org_identifier, kpi_type_code) sub\r\nwhere perfectMonth != 0"
    }
   ]
  },
  {
   "title": "Monthly Status Alert Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "select    device_identifier as devices, org_identifier as organizations, name as alerts,\r\n(CASE WHEN perfectMonth != 0 THEN 'Active' ELSE 'Inactive' END) as status\r\n    \t     from (\r\nselect  (avg(kpi_alert_count)) as perfectMonth, device_identifier, org_identifier, name\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nwhere   device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) \r\nAND name IN ($AlertList)\r\ngroup by TO_CHAR(time, 'YYYY-MM'), device_identifier,org_identifier, kpi_type_code, name) sub\r\norder by status desc"
    }
   ]
  },
  {
   "title": "% Monthly Inactive Alerts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN COUNT(CASE WHEN perfectMonth = 0 THEN 1 ELSE NULL END) = 0 THEN 0\r\n        ELSE (COUNT(CASE WHEN perfectMonth = 0 THEN 1 ELSE NULL END) * 100.0) / COUNT(*) \r\n    END as percentage\r\nFROM (\r\n    SELECT (avg(kpi_alert_count)) as perfectMonth\r\n    FROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\n    WHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) \r\nAND name IN ($AlertList)\r\n    GROUP BY TO_CHAR(time, 'YYYY-MM'), device_identifier, org_identifier, name\r\n) sub;"
    }
   ]
  },
  {
   "title": "Trend of Active vs Inactive Alerts",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select   COUNT(CASE WHEN perfectMonth != 0 THEN 1 ELSE NULL END) as \"active alerts\",\r\n    \tCOUNT(CASE WHEN perfectMonth = 0 THEN 1 ELSE NULL END) as \"inactive alerts\",\r\n    \tym from (\r\nselect  (avg(kpi_alert_count)) as perfectMonth, TO_CHAR(time, 'YYYY-MM') as ym\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nwhere  device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND name IN ($AlertList)\r\ngroup by TO_CHAR(time, 'YYYY-MM'), device_identifier, org_identifier, kpi_type_code) sub\r\ngroup by ym"
    }
   ]
  },
  { "title": "Alert Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Alert Condition",
   "type": "stat",
   "description": "Select only one alert!",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": " select distinct kpi_alert_condition_text_last  from kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\n where name IN ($AlertList);"
    }
   ]
  },
  {
   "title": "Monthly Data Alert Trend",
   "type": "timeseries",
   "description": "Select only one alert!",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 26 },
   "targets": [
    {
     "rawSql": "select avg(kpi_value_min) as \"min. value\" , avg(kpi_value_max) as \"max. value\" , avg(kpi_value_avg) as \"avg. value\", DATE_TRUNC('month', time)+  INTERVAL '14 days'\r\nfrom kpi_1d INNER JOIN kpi_type ON kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList)  \r\nAND name in ($AlertList)\r\ngroup by DATE_TRUNC('month', time)"
    }
   ]
  },
  {
   "title": "Daily Data Alert Trend",
   "type": "timeseries",
   "description": "Select only one Alert!",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select avg(kpi_value_min) as \"min. value\" , avg(kpi_value_max) as \"max. value\", avg(kpi_value_avg) as \"avg. value\" , time as Day\r\nfrom kpi_1d INNER JOIN kpi_type ON kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList)  \r\nAND name in ($AlertList)\r\ngroup by name,  time\r\n"
    }
   ]
  },
  {
   "title": "Min. Values of Alert",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "select \"min value\", TO_CHAR(time, 'YYYY-MM-DD') from (\r\nselect round(avg(kpi_value_min),2) as \"min value\" , TO_CHAR(time, 'YYYY-MM'), time \r\nfrom kpi_1d INNER JOIN kpi_type ON kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList)  \r\nAND name in ($AlertList)\r\nand TO_CHAR(time, 'YYYY-MM') in ($YearMonth )\r\ngroup by  time ) sub\r\n"
    }
   ]
  },
  {
   "title": "Max. Values of Alert",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "rawSql": "select  maximum, TO_CHAR(time, 'YYYY-MM-DD') from (\r\nselect round(avg(kpi_value_max),2) as maximum , TO_CHAR(time, 'YYYY-MM'), time \r\nfrom kpi_1d INNER JOIN kpi_type ON kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList)  \r\nAND name in ($AlertList)\r\nand TO_CHAR(time, 'YYYY-MM') in ($YearMonth )\r\ngroup by  time ) sub"
    }
   ]
  },
  {
   "title": "AVG. values of Alert",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "rawSql": "select  mean, TO_CHAR(time, 'YYYY-MM-DD') from (\r\nselect  round(avg(kpi_value_avg),2) as mean, TO_CHAR(time, 'YYYY-MM'), time \r\nfrom kpi_1d INNER JOIN kpi_type ON kpi_type.code = kpi_1d.kpi_type_code\r\nwhere device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList)  \r\nAND name in ($AlertList)\r\nand TO_CHAR(time, 'YYYY-MM') in ($YearMonth )\r\ngroup by  time ) sub"
    }
   ]
  }
 ]
}