{
 "title": "Home",
 "time": { "from": "2022-11-01T00:00:00.000Z", "to": "2023-05-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "DeviceList",
    "label": "Device",
    "query": "select distinct device_identifier from kpi_1d;"
   },
   {
    "name": "OrganizationList",
    "label": "Organization",
    "query": "select distinct org_identifier  from kpi_1d;"
   },
   {
    "name": "YearMonth",
    "label": "Period",
    "query": "SELECT distinct TO_CHAR (time, 'YYYY-MM') FROM kpi_1d;"
   },
   { "name": "Warning", "label": "Select only one Month!", "query": "Select only one Month!" }
  ]
 },
 "panels": [
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT device_identifier)\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nWHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) \r\n"
    }
   ]
  },
  {
   "title": "Total Organizations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT org_identifier)\r\nFROM kpi_1d inner join kpi_type on kpi_type.code = kpi_1d.kpi_type_code\r\nWHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth) \r\n"
    }
   ]
  },
  {
   "title": "Monthly Ideal Performance Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nCOUNT(CASE WHEN mean_devices = 0 THEN 1 ELSE NULL END)\r\nFROM (\r\n    SELECT  \r\n        AVG(kpi_alert_count) as mean_devices, \r\n        device_identifier, \r\n        TO_CHAR(time, 'YYYY-MM') as ym\r\n    FROM kpi_1d\r\n    WHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth)  \r\n    GROUP BY device_identifier, TO_CHAR(time, 'YYYY-MM')\r\n) sub"
    }
   ]
  },
  {
   "title": "Monthly Devices with Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nCOUNT(CASE WHEN mean_devices != 0 THEN 1 ELSE NULL END)\r\nFROM (\r\n    SELECT  \r\n        AVG(kpi_alert_count) as mean_devices, \r\n        device_identifier, \r\n        TO_CHAR(time, 'YYYY-MM') as ym\r\n    FROM kpi_1d\r\n    WHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth)  \r\n    GROUP BY device_identifier, TO_CHAR(time, 'YYYY-MM')\r\n) sub"
    }
   ]
  },
  {
   "title": "% Monthly Ideal Performance Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN COUNT(CASE WHEN mean_devices = 0 THEN 1 ELSE NULL END) = 0 THEN 0\r\n        ELSE (COUNT(CASE WHEN mean_devices = 0 THEN 1 ELSE NULL END) * 100.0) / COUNT(*)\r\n        END as percentage\r\nFROM (\r\n    SELECT  \r\n        AVG(kpi_alert_count) as mean_devices, \r\n        device_identifier, \r\n        TO_CHAR(time, 'YYYY-MM') as ym\r\n    FROM kpi_1d\r\n    WHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth)  \r\n    GROUP BY device_identifier, TO_CHAR(time, 'YYYY-MM')\r\n) sub"
    }
   ]
  },
  {
   "title": "Monthly Ideal Performance Devices",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN COUNT(CASE WHEN mean_devices = 0 THEN 1 ELSE NULL END) = 0 THEN 0\r\n        ELSE (COUNT(CASE WHEN mean_devices = 0 THEN 1 ELSE NULL END) * 100.0) / COUNT(*) \r\n    END as \"% Monthly Idea Performance Devices\", \r\n    COUNT(CASE WHEN mean_devices != 0 THEN 1 ELSE NULL END) as \"Devices with Alerts\",\r\n    COUNT(CASE WHEN mean_devices = 0 THEN 1 ELSE NULL END) as \"Ideal Performance Devices\", \r\n    ym \r\nFROM (\r\n    SELECT  \r\n        AVG(kpi_alert_count) as mean_devices, \r\n        device_identifier, \r\n        DATE_TRUNC('month', time) as ym\r\n    FROM kpi_1d\r\n    WHERE device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList)\r\n    GROUP BY device_identifier, DATE_TRUNC('month', time)\r\n) sub\r\nGROUP BY ym;"
    }
   ]
  },
  {
   "title": "Ideal Performance Devices List",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    device_identifier AS Device,\r\n    org_identifier as Organization,\r\n    COUNT(distinct CASE WHEN kpi_alert_count <> 0 THEN kpi_type_code END) as \"total alerts\"\r\nFROM kpi_1d\r\nWHERE  device_identifier IN ($DeviceList) \r\nAND org_identifier IN ($OrganizationList) \r\nAND TO_CHAR(time, 'YYYY-MM') IN ($YearMonth)\r\nGROUP BY\r\n    device_identifier,\r\n    TO_CHAR(time, 'YYYY-MM'),\r\n    Organization\r\norder by \"total alerts\" asc"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 } }
 ]
}